### ISSUE TITLE
PrintHex buffer initialization

### ISSUE THREAD

**Issue by ascended121** [UMDBPP/CCSDS_Xbee#5]
Right now the buffers used by printHex are fixed length, but the function currently doesn't check that the arguments don't overrun these buffers. Change the initialization of the buffers to be variable length based on the input arguments.

**Comment by nassif09** [comment]
Done

**Comment by ascended121** [comment]
Please update comments to reflect changes (update function description to indicate that it will cap the precision at 15 places, also remove the fixme's from the code if they're no longer relevant)

**Comment by nassif09** [comment]
Understood

**Comment by ascended121** [comment]
Also, the solution implemented currently (capping at 15 digits) will not allow the user to display uint32 (or larger) values, which may be useful. A better solution may be to declare the tmp and format arrays with the proper size based off the precision argument.

**Comment by ascended121** [comment]
Also, the more versatile solution might be to allocate the tmp and format arrays with the proper size based off the precision argument. This removes the (arbitrary) 15 digit limit for the user and should save (a small amount) of memory (since in most cases 15 digits won't be necessary).

**Comment by nassif09** [comment]
Can you check the edit I made?

**Comment by ascended121** [comment]
The precision values are initialized as int, but will never be negative, so half of the precision is being wasted. Also, int supports positive values up to 32767, but no data type can hold that many digits, so the values are much larger than needed.

Also, might be helpful to explain where the +2 and +6 come from for the buffers in the comments.

**Comment by nassif09** [comment]
I changed it to unsigned but I din't understand what you mean about 'no data type can hold that many digits'.

**Comment by ascended121** [comment]
The type of the num parameter (which is int) is a 32bit integer, capable of holding values between -32767 and 32767. So the entire range of values which can be stored by num can be printed using 5 digits (6 if you include the negative sign). unsigned int is an arduino alias for uint16_t, which is a 16 bit unsigned integer which can have values between 0 and 65535. So tmp_precision is capable of holding up to 65533 digits for a value which can only ever have 6... its slight overkill.

**Comment by nassif09** [comment]
Could you check it now?

I changed the tmp_precision to account for number of digits in precision and +2 for safety.
I'm not sure if that was right or the previous thing I did was right for tmp.

**Comment by ascended121** [comment]
So, just to clarify, this is just memory optimization... your code probably would've worked with the ints, but this is just something good to keep in mind as your coding.

I think what you have looks good in terms of code, but take a look at the form of the function... the values you calculate are unused if _debug_serial is false, so you have unnecessary code being executed in that case.

**Comment by ascended121** [comment]
Also, you have a random i on line 75 which is going to cause issues when you try to compile.

**Comment by nassif09** [comment]
Fixed the i, and I put the stuff I added under the if condition

**Comment by ascended121** [comment]
Made a couple of additional minor optimizations and updated comments
